#!/usr/bin/env bash

# redundant to delete both at start and end, but just in case
# these were left lying around...
rm -rf target-*/project-builds || true
rm -rf target-*/extraction || true

# TODO: in scala-jenkins-infra, make an actual parameter for
# specifying projects to be built, instead of hijacking the
# "scala_build_extra_opt" name for that purpose

export ANT_OPTS="-Dfile.encoding=UTF-8 -Xmx2G -Xss1M -Dpartest.threads=4 -Djava.io.tmpdir=/home/jenkins/tmp"
export JAVA_OPTS="-Dfile.encoding=UTF-8 -Xmx2G -Xss1M -Dpartest.threads=4 -Djava.io.tmpdir=/home/jenkins/tmp"
export MAVEN_OPTS="-Dfile.encoding=UTF-8 -Xmx2G -Xss1M -Dpartest.threads=4 -Djava.io.tmpdir=/home/jenkins/tmp"

./run.sh $scala_build_extra_opt || STATUS="$?"

# ideally we would keep these around for doing postmortems
# on failures, but we just don't have room on the behemoths
rm -rf target-*/project-builds
rm -rf target-*/extraction

exit $STATUS
